### ISSUE TITLE
JOSS review: paper proof read

### ISSUE THREAD

**Issue by hagenw** [sigsep/open-unmix-paper-joss#11]
The paper looks good, I have only some minor comments, that would be nice to address:

* There is a broken link for the PyTorch implementation, see https://github.com/sigsep/open-unmix-paper-joss/commit/3cba8981bafb00980ad658b4e68da35eb469cdcf#r34909982
* Some references are written with brackets when there shouldn't be one, e.g. 
> ... overview see (Rafii, Liutkus, Stöter, Mimilakis, & Bittner, 2017) and (Cano,
FitzGerald, Liutkus, Plumbley, & Stöter, 2019).
> ... was presented in (Ozerov, Vincent, & Bimbot,
2011; Salaün et al., 2014).

And at several other places, would be nice to fix those.

**Comment by faroit** [comment]
I addressed the first bullet, about the second one: I think this is the way how the JOSS templates handles multiple reference citations and I think `[@author1; @author2]` is the correct way to cite here in markdown. But I am happy to change this if there is a different option.

**Comment by hagenw** [comment]
I was not concerned about how the two authors are cited, but when you address a citation direct in text there shouldn't be any brackets around the whole block, but only around the year:
```
... overview see (Rafii, Liutkus, Stöter, Mimilakis, & Bittner, 2017) and (Cano,
FitzGerald, Liutkus, Plumbley, & Stöter, 2019)
```
should be
```
... overview see Rafii, et al. (2017) and Cano, et al. (2019)
```
but I guess you are right, and this is not possible with markdown.

**Comment by hagenw** [comment]
For me it's fine to stay with the current paper.
