### ISSUE TITLE
JOSS review: add community guidelines for sub-projects

### ISSUE THREAD

**Issue by hagenw** [sigsep/open-unmix-paper-joss#12]
I totally agree with the porposal in https://github.com/sigsep/open-unmix-paper-joss/issues/2#issuecomment-526620369 to include the other sub-projects as they are an important part of open-unmix.

In order to fulfill the community guidelines requirements asked for by JOSS, it would be nice if you could add the solution of #6 also to all the sub-projects as they are missing a `CONTRIBUTING.md`, but they would clearly benefit of having one as well.

**Comment by faroit** [comment]
Hi, we added this to `norbert`, `museval` and `musdb`. I decided to not do a issue templates for them since we don't except much issues there, so we can probably manage without.

I didn't update the tags since I believe it makes sense that they match to the zenodo release.

**Comment by hagenw** [comment]
Cool, thank you, this is totally fine with me.
