### ISSUE TITLE
Paper: absolute time, instead of relative time

### ISSUE THREAD

**Issue by arokem** [sigsep/open-unmix-paper-joss#14]
In addition to suggestions in #13, could you please change the sentence: "The library is written in Python 2.7. Unfortunately, it has not been updated since two years ago and many of its methods are not tested" into one that describes the absolute time of this, instead of relative: "The library is written in Python 2.7. Unfortunately, it has not been updated since 2017 and many of its methods are not tested"

**Comment by faroit** [comment]
Thanks, yes that would certainly make the statement more readable in the future. 
I updated your pull request #13 in 7ca1889 to accommodate this change
