### ISSUE TITLE
JOSS review: source code links?

### ISSUE THREAD

**Issue by bmcfee** [sigsep/open-unmix-paper-joss#3]
The JOSS review template asks if the source code is included in the submitted repo (ie this one, for the paper).

I think the answer here is broadly yes, by way of submodules, but it's not obvious at a glance which of the submodules are functional and which are stubs for future work.

If the README for this repo had an index that clarified this, it would be helpful.

As an aside, the readme in the pytorch implementation (and likely others) links to related projects denoted as "torch", "tensorflow", "nnabla", etc.  This is misleading, since they link to your repositories containing those respective implementations of UMX, and not the torch, tf, or nn projects themselves.  I suggest renaming those links.

**Comment by faroit** [comment]
thanks for this comment

> I think the answer here is broadly yes, by way of submodules, but it's not obvious at a glance which of the submodules are functional and which are stubs for future work.

I added a description to the readme which submodules are finished and which are under development. I think this is related to #2 

> As  an aside, the readme in the pytorch implementation (and likely others)  links to related projects denoted as "torch", "tensorflow", "nnabla",  etc.  This is misleading, since they link to your repositories  containing those respective implementations of UMX, and not the torch,  tf, or nn projects themselves.  I suggest renaming those links.

I have updated the breadcrumb in all of the related repos

**Comment by bmcfee** [comment]
Awesome, thanks!
