### ISSUE TITLE
JOSS review: community guidelines

### ISSUE THREAD

**Issue by bmcfee** [sigsep/open-unmix-paper-joss#6]
The JOSS reviewer instructions list the following points for community guidelines:

-    Contribute to the software
-    Report issues or problems with the software
-    Seek support

There is a bit in the readme addressing the first point, but the second and third points are not addressed.  In general, a contributing.md document and issue templates would be great additions.

**Comment by faroit** [comment]
thanks for the comment. 

The mentioned points have been addressed in the [pytorch submodule](https://github.com/sigsep/open-unmix-pytorch/tree/469c0742cbafb285108543a432bfaa4b6a3f0dac). The contribution guidelines will be added to the nnabla and tensorflow modules once they are stable.

Regarding `seek support`, we have not explicitly addressed this point yet. Can you give an example of how we can phrase that __support is done via github issues__?

**Comment by bmcfee** [comment]
> Can you give an example of how we can phrase that **support is done via github issues**?

I can't think of any off-hand, but I think a link to the issues page with a comment to the effect of "bug reports and requests for technical support should be submitted through github issues" would be sufficient.

**Comment by faroit** [comment]
alright. [I addressed this](https://github.com/sigsep/open-unmix-pytorch/commit/f0c87f9d43a6dd440702349e73f685a509721f26)
