### ISSUE TITLE
DOIs for some references are missing

### ISSUE THREAD

**Issue by hagenw** [sigsep/open-unmix-paper-joss#8]
Please add DOIs for the following references in `paper.bib`:

* `ozerov2011general`, `10.1109/TASL.2011.2172425`
* `chandna17`, `10.1007/978-3-319-53547-0_25`
* `sisec10`, `10.1016/j.sigpro.2011.10.007`
* `sisec11`, `10.1007/978-3-642-28551-6_51`

And also please to the following (without proposals ;) ):
* `sisec13`
* `sisec15`
* `sisec16`
* `sisec18`
* `cano19`
* `uhlich17`
* `uhlich15`
* `nugraha16`
* `sivasankaran2015robust`
* `le2019phasebook`
* `takahashi2018phasenet`
* `mcfee2018open`

Please correct the DOI entry in:
* `rafii17` (not shown in paper)

**Comment by faroit** [comment]
@TE-StefanUhlich can you check these, please?

**Comment by StefanUhlich-sony** [comment]
ok, I will check them and create a PR
