### ISSUE TITLE
Tests for the different implementations vary

### ISSUE THREAD

**Issue by hagenw** [sigsep/open-unmix-paper-joss#9]
The implementation of [open-unmix-pytorch](https://github.com/sigsep/open-unmix-pytorch) contains a reasonable amount of nice tests.

The same cannot be stated for [open-unmix-nnabla](https://github.com/sigsep/open-unmix-nnabla) which only contains a test for `stft`, and [open-unmix-tensorflow](https://github.com/sigsep/open-unmix-tensorflow), which does not contain any code/tests (see also https://github.com/sigsep/open-unmix-paper-joss/issues/2#issuecomment-526094678).

In my opinion this is fine if the structure of the paper would change with a focus on [open-unmix-pytorch](https://github.com/sigsep/open-unmix-pytorch) and mentioning the other packages only as additions. Otherwise I would expect a similar amount of tests in all three packages.

**Comment by faroit** [comment]
> The same cannot be stated for open-unmix-nnabla which only contains a test for stft

For now, we cannot test the nnabla model on travis as the framework requires cudnn to run the LSTM layer. 

> In my opinion this is fine if the structure of the paper would change with a focus on open-unmix-pytorch and mentioning the other packages only as additions. 

See #2

**Comment by faroit** [comment]
@hagenw  SInce a decision was made in #2, this can be closed, right?

**Comment by hagenw** [comment]
Yes, this is solved by #2.
